name: Docs
permissions:
  contents: read

on: [push, pull_request]

env:
  IS_RELEASE: |
    ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Install Python dependencies
        run: pip install -r requirements-doc.txt

      - name: Install mpl-gui
        run: python -m pip install -v .
      - name: Build
        run: |
          if [ "x${IS_RELEASE}" == "xtrue" ]; then
            O="-t release"
          fi
          make -Cdocs html O="$O"

      - name: Publish
        if: ${{ env.IS_RELEASE == 'true' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true
